### ISSUE TITLE
Need help with raw file input

### ISSUE THREAD

**Issue by Hkokash** [guilindner/VortexFitting#14]
I am trying to anaylze my own data, in a form of .raw input that imitates the same as "example_Ub_planeZ_0.01.raw" and this is how it looks for the first 10 lines, the total number of points are 4489

#  x  y  z  Ub_x  Ub_y  Ub_z
-0.026 -0.108 0.1 3.6032746E-01 -2.6343218E-01 -2.7512721E-14
-0.026 -0.107 0.1 4.1568081E-01 -2.3964616E-01 -2.7216987E-14
-0.026 -0.106 0.1 4.3013102E-01 -2.5783025E-01 -2.8222474E-14
-0.026 -0.105 0.1 4.1832238E-01 -2.7004882E-01 -3.2233660E-14
-0.026 -0.104 0.1 3.9437116E-01 -2.7234528E-01 -2.9028621E-14
-0.026 -0.103 0.1 3.7255704E-01 -2.7737633E-01 -2.0115354E-14
-0.026 -0.102 0.1 3.5646389E-01 -2.8840296E-01 -1.1919489E-14
-0.026 -0.101 0.1 3.4317864E-01 -3.0203246E-01 -8.1622595E-15
-0.026 -0.1 0.1 3.2906472E-01 -3.1490539E-01 -8.4730209E-15
-0.026 -0.099 0.1 3.1237062E-01 -3.2627518E-01 -1.0440682E-14

However, when I run this code:
import os
import sys

is_windows = sys.platform.startswith('win')

if is_windows:
    print("Running on Windows ...")
else:
    print("Running on Linux ...")

if sys.version_info[0] < 3:
    raise Exception("Must be using Python 3")
else:

    cmd = 'python3 run.py -i data/test.raw ' \
          '-ft openfoam -d swirling -s 4 -p fields -o results/testing -rmax 0'
    os.system(cmd)

    cmd = 'python3 run.py -i data/test.raw ' \
        '-ft openfoam -o results/testing -rmax 0'
    os.system(cmd)

I get this error:

Running on Linux ...

Opening file:  data/test.raw , file type:  openfoam
No w velocity matrix
Difference scheme: Fourth Order Scheme
Detection method: 2D swirling strength
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    vortexfitting.__main__.main()
  File "/home/hf9098/PycharmProjects/VortexFitting/vortexfitting/__main__.py", line 150, in main
    detection_field = detection.calc_swirling(vfield)
  File "/home/hf9098/PycharmProjects/VortexFitting/vortexfitting/detection.py", line 29, in calc_swirling
    eigenvalues = np.linalg.eigvals(matrix_a)
  File "<__array_function__ internals>", line 6, in eigvals
  File "/home/hf9098/PycharmProjects/VortexFitting/venv/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 1048, in eigvals
    _assert_finite(a)
  File "/home/hf9098/PycharmProjects/VortexFitting/venv/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 218, in _assert_finite
    raise LinAlgError("Array must not contain infs or NaNs")
numpy.linalg.LinAlgError: Array must not contain infs or NaNs

Opening file:  data/test.raw , file type:  openfoam
No w velocity matrix
Difference scheme: least-square filter
Detection method: 2D swirling strength
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    vortexfitting.__main__.main()
  File "/home/hf9098/PycharmProjects/VortexFitting/vortexfitting/__main__.py", line 150, in main
    detection_field = detection.calc_swirling(vfield)
  File "/home/hf9098/PycharmProjects/VortexFitting/vortexfitting/detection.py", line 29, in calc_swirling
    eigenvalues = np.linalg.eigvals(matrix_a)
  File "<__array_function__ internals>", line 6, in eigvals
  File "/home/hf9098/PycharmProjects/VortexFitting/venv/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 1048, in eigvals
    _assert_finite(a)
  File "/home/hf9098/PycharmProjects/VortexFitting/venv/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 218, in _assert_finite
    raise LinAlgError("Array must not contain infs or NaNs")
numpy.linalg.LinAlgError: Array must not contain infs or NaNs

Process finished with exit code 0

Any possible cause and solution?

**Comment by ydevau01** [comment]
Hello,
Thank you for using VortexFitting !

Did you check your data, are you sure there is no NaN values in your velocity field, for u or v component ?
Here, the first command line fails to compute the swirling, even one NaN value could be a problem.

**Comment by Hkokash** [comment]
Thanks for the reply, actually there is no NaN values in the velocity field, and that is why I am wondering if there is any other parameters that should be in the data file. However, some values are up to E-15, I don't know if they affect how the code runs.

I have attached the .raw file if that will do any help.




[test.zip](https://github.com/guilindner/VortexFitting/files/10310231/test.zip)

**Comment by ydevau01** [comment]
Okay, I looked at your data, I think the problem is the order of x and y. 
In the example, the first variable varying is x, then y. In your file, y changes before x. 
When the spatial data are read and reshaped, I think it produces a constant matrix for x and for y, which lead to NaN values when derivatives are calculated.
If you can modify the writing order for your data, it will solve this issue !

(file example_Ub_planeZ_0.01.raw
#  x  y  z  Ub_x  Ub_y  Ub_z  
0.0005 0.0005 0.02 0.009247 -0.038286 -0.038286
0.0015 0.0005 0.02 0.003664 -0.0254063 -0.0254063
...

file test.raw
#  x  y  z  Ub_x  Ub_y  Ub_z
-0.026 -0.108 0.1 3.6032746E-01 -2.6343218E-01 -2.7512721E-14
-0.026 -0.107 0.1 4.1568081E-01 -2.3964616E-01 -2.7216987E-14
...)

**Comment by Hkokash** [comment]
Interesting, I will test it out!
Appreciate your effort, thank you!

**Comment by Hkokash** [comment]
Hello again,

After rearranging x and y, layout It seems that the error has changed to:

Opening file:  data/test.raw , file type:  openfoam
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    vortexfitting.__main__.main()
  File "/home/hf9098/PycharmProjects/VortexFitting/vortexfitting/__main__.py", line 124, in main
    vfield = classes.VelocityField(args.input_filename, time_step, args.mean_filename, args.file_type)
  File "/home/hf9098/PycharmProjects/VortexFitting/vortexfitting/classes.py", line 250, in __init__
    self.y_coordinate_size)
ValueError: cannot reshape array of size 4487 into shape (66,67)

Opening file:  data/test.raw , file type:  openfoam
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    vortexfitting.__main__.main()
  File "/home/hf9098/PycharmProjects/VortexFitting/vortexfitting/__main__.py", line 124, in main
    vfield = classes.VelocityField(args.input_filename, time_step, args.mean_filename, args.file_type)
  File "/home/hf9098/PycharmProjects/VortexFitting/vortexfitting/classes.py", line 250, in __init__
    self.y_coordinate_size)
ValueError: cannot reshape array of size 4487 into shape (66,67)

Process finished with exit code 0


Does that mean that I have to match the number of coordinates in  example_Ub_planeZ_0.01x.raw file (10000 coordinates)?

**Comment by ydevau01** [comment]
this time, I think it may be an error in the data:
The error says "cannot reshape array of size 4487 into shape (66,67)", your initial file was of 4489 size (shape: 67x67), are your sure that your new file contains all the previous data ?

**Comment by Hkokash** [comment]
Absolutely correct! I am getting some results now.

One final question please, what is the cause of "No w velocity matrix" and "No w velocity" although the data file has Ub_z (w velocity) in it.

**Comment by ydevau01** [comment]
Good news ! 

For the  "No w velocity matrix", you are right, it is not normal. 
I found a mistake in classes.py, the index for w data is wrong, I will correct this ! 
(currently, the code contains this line:

>  index_x, index_y, index_z, index_u, index_v, index_w = 0, 1, 2, 3, 4, 6

but, of course, with data on 6 columns, following the example, it has to be:
> index_x, index_y, index_z, index_u, index_v, index_w = 0, 1, 2, 3, 4, **5**

**Comment by Hkokash** [comment]
Hello and sorry for the late feedback, it is all sorted out now.

Thanks again for your contribution and all the best!
